[package]
name = "johnameyer-advent-of-code"
version = "0.1.0"
authors = ["John (Jack) Meyer <jack10042@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
